-- Update charity_works table with the new high-fidelity data provided
DELETE FROM charity_works;

INSERT INTO charity_works (title, subtitle, category, description, location, order_index, image_url)
VALUES 
('Supporting Widows With Dignity', 'Providing stability, essentials, and livelihood support to women who shoulder families alone.', 'CHARITY', 'One of the earliest pillars of Mohsin’s philanthropic work focused on widows, women navigating life with limited income, security, and heavy responsibilities. Through direct support, monthly essentials, emergency aid and income-generating tools such as sewing machines and livestock, these women received more than assistance; they received stability, respect, and the chance to rebuild their lives with dignity.', 'Global', 0, '/assets/philanthropy.webp'),
('Early Humanitarian Relief- Food Security', 'Nourishing households across rural villages and low-income communities.', 'CHARITY', 'Consistent food distribution has been a core programme from the start, including grocery packs for over 200 families, cooked meals for elderly groups, and essentials delivered to communities with limited access. These initiatives ensured families had reliable access to essential nourishment and support. Each drive reflected the philosophy that relief should be offered quickly, with respect, and consistency.', 'Rural Villages', 1, '/assets/real-estate.jpg'),
('Health & Safety Support- Rural Villages', 'Blankets & Mosquito Nets for 14 Villages', 'CHARITY', 'Across multiple villages, blankets and mosquito nets were distributed to protect families from harsh temperatures and mosquito-borne disease. What may seem simple carries profound impact, warmth for the elderly, protection for children, and dignity for households that endure the cold without adequate coverings. These drives supported 14 villages and reinforced the belief that small acts, when done consistently, save lives.', '14 Villages', 2, '/assets/luxury-retail.jpg'),
('Supporting Orphans & Young Learners', 'Education, essentials and holistic support for children without stable foundations.', 'CHARITY', 'Several initiatives focused on children, from orphan support to school essentials, clothing, meals, and early education materials. These programmes ensured that some of the world’s most vulnerable young minds received nourishment, guidance, and the grounding needed to grow confidently. Mohsin’s philosophy remains simple: every child deserves a childhood anchored in stability and hope.', 'Global', 3, '/assets/podcast-interview.jpg'),
('Distributing 25 Small Businesses', 'Creating pathways to self-reliance for families.', 'CHARITY', 'One of the largest livelihood-focused drives included gifting 25 full small-business setups, tools, stock, or equipment that allowed recipients to generate income immediately. From shop inventory to trade kits, each setup was customised to a family’s skill or need, shifting charity from one-time support to long-term empowerment. This initiative reinforced the foundation’s commitment to sustainable upliftment.', 'Global', 4, '/assets/fashion-model.jpg'),
('Supporting Daily Wage Earners', 'Aid designed around physical, economic, and social challenges.', 'CHARITY', 'Rickshaw pullers and persons with disabilities often belong to segments with the least safety nets. By offering equipment, repairs, financial assistance, and mobility support, these initiatives helped restore dignity and earning capacity. These were not mass drives; they were deeply personal interventions tailored to individual need, reflecting compassion grounded in understanding.', 'Global', 5, '/assets/real-estate.jpg'),
('Gifting Livestock for Livelihoods', '52 goats and 7 dairy cows were gifted to families in need.', 'CHARITY', 'In several villages, goats and dairy cows were provided to households with limited earning opportunities. Livestock offers recurring income through milk, breeding, and sales, becoming a renewable asset rather than a short-term donation. These initiatives especially benefited widows, single mothers, and families in remote areas, grounding financial stability in sustainable rural economies.', 'Remote Villages', 6, '/assets/philanthropy.webp'),
('Multi-Village Relief Programmes', 'Serving 6 villages with food, supplies, and essentials.', 'CHARITY', 'In larger-scale efforts, entire villages received essentials like food packs, hygiene items, clothing, children’s supplies, and basic medicine. These drives were structured to ensure equitable distribution, reaching the elderly, disabled, widows, and children first. The outcome was not only immediate relief, but restored hope in communities that often feel forgotten.', '6 Villages', 7, '/assets/luxury-retail.jpg'),
('Ramadan & Eid Relief Distribution', 'Food and essentials delivered across thousands of households.', 'CHARITY', 'Every year, during Ramadan and Eid, the foundation carries out widespread distribution drives of groceries, meals, essentials, and emergency relief. These sacred-month programmes reach families across regions and countries, reflecting Mohsin’s belief that gratitude must be shared, especially during times of spiritual importance. It is one of the longest-standing traditions in his philanthropic journey.', 'Global', 8, '/assets/podcast-interview.jpg'),
('Building Homes for Families', 'Construction and gifting of permanent houses.', 'CHARITY', 'From gifting multiple fully-built houses to supporting widows with safe accommodation, housing initiatives represent the most transformative tier of support. These homes provide families with long-term security, drastically improving education, health, and livelihood prospects. For Mohsin, a house is not charity; it is the foundation for a stable, dignified life.', 'Global', 9, '/assets/real-estate.jpg'),
('Rural Water Relief', 'Creating access to clean drinking water.', 'CHARITY', 'In regions where clean water is scarce, the foundation supported the construction of wells and the distribution of safe water solutions. These projects reduce disease, save hours of daily labour, and drastically improve the quality of life, especially for women and children who walk miles each day for water. It is one of the most life-changing forms of charity.', 'Remote Regions', 10, '/assets/philanthropy.webp'),
('One-on-One Humanitarian Support', 'Helping individuals facing crisis, illness, or extreme hardship.', 'CHARITY', 'Many videos reflect deeply personal support: assisting elderly individuals, patients requiring financial help, families recovering from loss, and people struggling with disabilities. These are not large campaigns; they are quiet acts of compassion. They reflect the belief that impact is not measured by scale, but by sincerity.', 'Individual Cases', 11, '/assets/podcast-interview.jpg');
